# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNIconic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNIconic

  pod 'VBFPopFlatButton', :git => 'https://github.com/prscX/VBFPopFlatButton.git', :commit => '5ac6e640b85ed534f4d06465bfe3e5f9f114b01b'
end
